[package]
name = "th"
version = "0.1.0"
edition = "2021"
# 作者
authors = ["ximoqing <ximoqing@gmail.com>"]
# 关键词
keywords = ["macros", "th"]
# 许可证
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
